### ISSUE TITLE
Missing remoteDisconnected as dependency

### ISSUE THREAD

**Issue by ADeane6** [barrycarey/Plex-Data-Collector-For-InfluxDB#10]
Seems that when I run this with python 3.4.3, influxdb and request installed 
I get the following error

` from http.client import RemoteDisconnected
ImportError: cannot import name 'RemoteDisconnected'`

Any ideas

**Comment by bgulla** [comment]
seeing this as well.

**Comment by bboy8012** [comment]
I found if you run with python 3.5 the object RemoteDisconnected is in it.

**Comment by jinglyjangles** [comment]
@ADeane6 @bgulla  Had the same issue in 3.4, ran 3.6.5 in a virtual environment (i.e. virutalenv -p python3.6) and was finally able to get it working.
