### ISSUE TITLE
ModuleNotFoundError: No module named "influxdb"

### ISSUE THREAD

**Issue by hwwilliams** [barrycarey/Plex-Data-Collector-For-InfluxDB#11]
I have influxdb installed and I get this error when running the .py.

![shot_170614_013130](https://user-images.githubusercontent.com/20447447/27116805-3993d5aa-50a1-11e7-9c10-bd0653c2cf7a.png)

**Comment by ZoesDev** [comment]
did you install the python3 influxdb module?  it is a separate package on ubuntu

**Comment by hwwilliams** [comment]
Got it thanks.
