### ISSUE TITLE
Want: Terminate script after one poll

### ISSUE THREAD

**Issue by audioeptesicus** [barrycarey/Plex-Data-Collector-For-InfluxDB#14]
I'd like to have the script terminate after one poll. The reason for this is so that I can create a bash script and service in Ubuntu to run the script every 10 seconds, while giving me the ability to start and stop the service without having to run the script manually or rely on crontab.

What will I need to include in the script, and where, to be able to exit it after one poll cycle?

**Comment by azlux** [comment]
I didn't do the changes, but the code show the https://github.com/barrycarey/Plex-Data-Collector-For-InfluxDB/blob/master/plexInfluxdbCollector.py#L481

You need to replace 
```
        while True:
            self.get_library_data()
            self.get_active_streams()
            time.sleep(self.delay)
```
by something like 
```
        self.get_library_data()
        self.get_active_streams()
        exit(0)
```
I will make a pull request if I have time and motivation to use this project.

**Comment by azlux** [comment]
But it's for now, not a good idea. The script try to authenticate the user at every start (on plex.tv)

**Comment by barrycarey** [comment]
Newest update a --singlerun argument you can pass in to abort after 1 run.

**Comment by azlux** [comment]
For single-Run, can you store the token into a file, to avoid the authentication on every run ?
