### ISSUE TITLE
Delay setting (seconds or minutes)?

### ISSUE THREAD

**Issue by n1nj4888** [barrycarey/Plex-Data-Collector-For-InfluxDB#20]
The "Delay" setting in config.ini is listed as the following on your github landing page for the Plex-Data-Collector-For-InfluxDB:

Delay = Delay between updating metrics

Could you please confirm the units for this Delay? For example, If I enter "1" is that every second or every minute?

Thanks!

**Comment by azlux** [comment]
This value is in second.

**Comment by n1nj4888** [comment]
Ok thanks for this. And the default delay of every 2 seconds is recommended as this sounds a little excessive?

**Comment by barrycarey** [comment]
2 is probably excessive.  Feel free to change it to anything you want.
