### ISSUE TITLE
Not collecting Season/Episodes Data

### ISSUE THREAD

**Issue by RetroDadson** [barrycarey/Plex-Data-Collector-For-InfluxDB#24]
This doesn't appear to be logging either Season or Episode data into influxDB, is showing number of TV Shows though, 

This is being run in docker, although has been run outside of docker, 

Plex is version 1.13.8.5395 (also run in docker)

**Comment by Soitora** [comment]
Same issue here

**Comment by RetroDadson** [comment]
Hi Soiotra, 

I worked the problems causing this out,

1. The Grafana dashboard has specific libraries specified, which may need altering to the correct name library for your plex install
2. Within the python code it has a name specifically for the library type instead of using the library type property. 

I have resolved this within a Fork found [here](https://github.com/dads07a/Plex-Data-Collector-For-InfluxDB). This has also been pull requested for this repo however I am waiting for Barry to accept the pull. 

Thanks

Robin
